version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5003:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data/

volumes:
  keycloak-data: